<?php

class Event extends BaseModel {
    /**
     * The database collection
     *
     * @var string
     */
    protected $collection = 'events';

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = array(
        'name'              => 'required',
        'description'       => 'required',
        'occurs_at'         => 'required|date'
    );

    /**
     * Setable with the fill method
     */
    public $fillable = array();

    /**
     * Attributes that will be generated by FactoryMuff
     */
    public static $factory = array(
        'name' => 'text',
        'description' => 'text',
        'occurs_at' => 'date'
    );
}
